#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# generated by wxGlade 0.6.6 on Fri Feb 28 15:19:38 2014
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ControlFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ControlFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.btnLoad = wx.Button(self, wx.ID_ANY, u"Загрузить управление")
        self.btnExecute = wx.Button(self, wx.ID_ANY, u"Выполнить")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnLoad_handler, self.btnLoad)
        self.Bind(wx.EVT_BUTTON, self.btnExecute_handler, self.btnExecute)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ControlFrame.__set_properties
        self.SetTitle(u"Управление заданиями")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ControlFrame.__do_layout
        sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(self.btnLoad, 0, wx.EXPAND, 0)
        sizer_1.Add(self.btnExecute, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def btnLoad_handler(self, event):  # wxGlade: ControlFrame.<event_handler>
        print "Event handler 'btnLoad_handler' not implemented!"
        event.Skip()

    def btnExecute_handler(self, event):  # wxGlade: ControlFrame.<event_handler>
        print "Event handler 'btnExecute_handler' not implemented!"
        event.Skip()

# end of class ControlFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frameCtrl = ControlFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frameCtrl)
    frameCtrl.Show()
    app.MainLoop()