#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Apr  6 19:24:36 2014

import wx

# begin wxGlade: extracode
# end wxGlade



class WavSources(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: WavSources.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.comboProfiles = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.btnSaveAs = wx.Button(self, -1, u"Сохранить как...")
        self.btnDelete = wx.Button(self, -1, u"Удалить")
        self.lbWavFiles = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE|wx.LB_ALWAYS_SB)
        self.label_1 = wx.StaticText(self, -1, "phi")
        self.textPhi = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER)
        self.label_2 = wx.StaticText(self, -1, "theta")
        self.textTheta = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER)
        self.label_3 = wx.StaticText(self, -1, "L")
        self.textL = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER)
        self.btnAddFiles = wx.Button(self, -1, u"Добавить")
        self.btnRemoveFiles = wx.Button(self, -1, u"Удалить")
        self.btnMoveUp = wx.Button(self, -1, u"Вверх")
        self.btnMoveDown = wx.Button(self, -1, u"Вниз")
        self.btnExecute = wx.Button(self, -1, u"Обработать")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.comboProfiles_on_combo, self.comboProfiles)
        self.Bind(wx.EVT_BUTTON, self.btnSaveAs_on_click, self.btnSaveAs)
        self.Bind(wx.EVT_BUTTON, self.btnDelete_on_click, self.btnDelete)
        self.Bind(wx.EVT_LISTBOX, self.lbWavFiles_on_click, self.lbWavFiles)
        self.Bind(wx.EVT_TEXT_ENTER, self.textPhi_on_enter, self.textPhi)
        self.Bind(wx.EVT_TEXT_ENTER, self.textTheta_on_enter, self.textTheta)
        self.Bind(wx.EVT_TEXT_ENTER, self.textL_on_enter, self.textL)
        self.Bind(wx.EVT_BUTTON, self.btnAddFiles_handler, self.btnAddFiles)
        self.Bind(wx.EVT_BUTTON, self.btnRemoveFiles_handler, self.btnRemoveFiles)
        self.Bind(wx.EVT_BUTTON, self.btnMoveUp_handler, self.btnMoveUp)
        self.Bind(wx.EVT_BUTTON, self.btnMoveDown_handler, self.btnMoveDown)
        self.Bind(wx.EVT_BUTTON, self.btnExecute_handler, self.btnExecute)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WavSources.__set_properties
        self.SetTitle(u"Анализ wav-файлов")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WavSources.__do_layout
        sizer_1 = wx.FlexGridSizer(4, 1, 0, 0)
        sizer_2 = wx.GridSizer(3, 4, 0, 0)
        sizer_3 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_3.Add(self.comboProfiles, 0, wx.EXPAND, 0)
        sizer_3.Add(self.btnSaveAs, 0, 0, 0)
        sizer_3.Add(self.btnDelete, 0, 0, 0)
        sizer_3.AddGrowableCol(0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(self.lbWavFiles, 0, wx.EXPAND, 0)
        sizer_2.Add(self.label_1, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.textPhi, 0, wx.EXPAND, 0)
        sizer_2.Add(self.label_2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.textTheta, 0, wx.EXPAND, 0)
        sizer_2.Add(self.label_3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.textL, 0, wx.EXPAND, 0)
        sizer_2.Add((10, 10), 0, 0, 0)
        sizer_2.Add((10, 10), 0, 0, 0)
        sizer_2.Add(self.btnAddFiles, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btnRemoveFiles, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btnMoveUp, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btnMoveDown, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.btnExecute, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.AddGrowableRow(1)
        sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def comboProfiles_on_combo(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `comboProfiles_on_combo' not implemented!"
        event.Skip()

    def btnSaveAs_on_click(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `btnSaveAs_on_click' not implemented!"
        event.Skip()

    def btnDelete_on_click(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `btnDelete_on_click' not implemented!"
        event.Skip()

    def lbWavFiles_on_click(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `lbWavFiles_on_click' not implemented!"
        event.Skip()

    def textPhi_on_enter(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `textPhi_on_enter' not implemented!"
        event.Skip()

    def textTheta_on_enter(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `textTheta_on_enter' not implemented!"
        event.Skip()

    def textL_on_enter(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `textL_on_enter' not implemented!"
        event.Skip()

    def btnAddFiles_handler(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `btnAddFiles_handler' not implemented!"
        event.Skip()

    def btnRemoveFiles_handler(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `btnRemoveFiles_handler' not implemented!"
        event.Skip()

    def btnMoveUp_handler(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `btnMoveUp_handler' not implemented!"
        event.Skip()

    def btnMoveDown_handler(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `btnMoveDown_handler' not implemented!"
        event.Skip()

    def btnExecute_handler(self, event): # wxGlade: WavSources.<event_handler>
        print "Event handler `btnExecute_handler' not implemented!"
        event.Skip()

# end of class WavSources


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    wav_sources = WavSources(None, -1, "")
    app.SetTopWindow(wav_sources)
    wav_sources.Show()
    app.MainLoop()
