#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# generated by wxGlade 0.6.6 on Sun Mar  9 21:03:57 2014
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class WavTasks(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: WavTasks.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.lbWavFiles = wx.ListBox(self, wx.ID_ANY, choices=[], style=wx.LB_MULTIPLE)
        self.btnAddFiles = wx.Button(self, wx.ID_ANY, u"Добавить")
        self.btnRemoveFiles = wx.Button(self, wx.ID_ANY, u"Удалить")
        self.btnMoveUp = wx.Button(self, wx.ID_ANY, u"Вверх")
        self.btnMoveDown = wx.Button(self, wx.ID_ANY, u"Вниз")
        self.btnExecute = wx.Button(self, wx.ID_ANY, u"Обработать")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnAddFiles_handler, self.btnAddFiles)
        self.Bind(wx.EVT_BUTTON, self.btnRemoveFiles_handler, self.btnRemoveFiles)
        self.Bind(wx.EVT_BUTTON, self.btnMoveUp_handler, self.btnMoveUp)
        self.Bind(wx.EVT_BUTTON, self.btnMoveDown_handler, self.btnMoveDown)
        self.Bind(wx.EVT_BUTTON, self.btnExecute_handler, self.btnExecute)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WavTasks.__set_properties
        self.SetTitle(u"Анализ wav-файлов")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WavTasks.__do_layout
        sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        sizer_2 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(self.lbWavFiles, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btnAddFiles, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btnRemoveFiles, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btnMoveUp, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btnMoveDown, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.btnExecute, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.AddGrowableRow(0)
        sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def btnAddFiles_handler(self, event):  # wxGlade: WavTasks.<event_handler>
        print "Event handler 'btnAddFiles_handler' not implemented!"
        event.Skip()

    def btnRemoveFiles_handler(self, event):  # wxGlade: WavTasks.<event_handler>
        print "Event handler 'btnRemoveFiles_handler' not implemented!"
        event.Skip()

    def btnMoveUp_handler(self, event):  # wxGlade: WavTasks.<event_handler>
        print "Event handler 'btnMoveUp_handler' not implemented!"
        event.Skip()

    def btnMoveDown_handler(self, event):  # wxGlade: WavTasks.<event_handler>
        print "Event handler 'btnMoveDown_handler' not implemented!"
        event.Skip()

    def btnExecute_handler(self, event):  # wxGlade: WavTasks.<event_handler>
        print "Event handler 'btnExecute_handler' not implemented!"
        event.Skip()

# end of class WavTasks
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    wav_tasks = WavTasks(None, wx.ID_ANY, "")
    app.SetTopWindow(wav_tasks)
    wav_tasks.Show()
    app.MainLoop()