#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# generated by wxGlade 0.6.6 on Thu May 29 14:56:28 2014
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class CompareResultsFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CompareResultsFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.btnRefresh = wx.Button(self, wx.ID_ANY, u"Обновить")
        self.btnClear = wx.Button(self, wx.ID_ANY, u"Очистить")
        self.btnSave = wx.Button(self, wx.ID_ANY, u"Сохранить")
        self.btnLoad = wx.Button(self, wx.ID_ANY, u"Загрузить")
        self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=[u"Столбцы по шаблонам", u"Столбцы по достоверности"], style=wx.CB_DROPDOWN | wx.CB_DROPDOWN | wx.CB_READONLY)
        self.gridCmpResults = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.textCompareInfo = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnRefresh_on_click, self.btnRefresh)
        self.Bind(wx.EVT_BUTTON, self.btnClear_on_click, self.btnClear)
        self.Bind(wx.EVT_BUTTON, self.btnSave_on_click, self.btnSave)
        self.Bind(wx.EVT_BUTTON, self.btnLoad_on_click, self.btnLoad)
        self.Bind(wx.grid.EVT_GRID_CMD_SELECT_CELL, self.gridCmpResults_on_cell_select, self.gridCmpResults)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CompareResultsFrame.__set_properties
        self.SetTitle(u"Результаты сравнения шаблонов")
        self.SetSize((800, 600))
        self.combo_box_1.SetSelection(0)
        self.gridCmpResults.CreateGrid(0, 1)
        self.gridCmpResults.EnableEditing(0)
        self.gridCmpResults.SetSelectionMode(wx.grid.Grid.wxGridSelectRows)
        self.gridCmpResults.SetColLabelValue(0, u"Смещение")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CompareResultsFrame.__do_layout
        sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(1, 5, 0, 0)
        grid_sizer_1.Add(self.btnRefresh, 0, 0, 0)
        grid_sizer_1.Add(self.btnClear, 0, 0, 0)
        grid_sizer_1.Add(self.btnSave, 0, 0, 0)
        grid_sizer_1.Add(self.btnLoad, 0, 0, 0)
        grid_sizer_1.AddGrowableCol(4)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.combo_box_1, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.gridCmpResults, 1, wx.ALL | wx.EXPAND, 0)
        grid_sizer_3.AddGrowableRow(1)
        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.textCompareInfo, 0, wx.ALL | wx.EXPAND, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.AddGrowableRow(1)
        sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def btnRefresh_on_click(self, event):  # wxGlade: CompareResultsFrame.<event_handler>
        print "Event handler 'btnRefresh_on_click' not implemented!"
        event.Skip()

    def btnClear_on_click(self, event):  # wxGlade: CompareResultsFrame.<event_handler>
        print "Event handler 'btnClear_on_click' not implemented!"
        event.Skip()

    def btnSave_on_click(self, event):  # wxGlade: CompareResultsFrame.<event_handler>
        print "Event handler 'btnSave_on_click' not implemented!"
        event.Skip()

    def btnLoad_on_click(self, event):  # wxGlade: CompareResultsFrame.<event_handler>
        print "Event handler 'btnLoad_on_click' not implemented!"
        event.Skip()

    def gridCmpResults_on_cell_select(self, event):  # wxGlade: CompareResultsFrame.<event_handler>
        print "Event handler 'gridCmpResults_on_cell_select' not implemented!"
        event.Skip()

# end of class CompareResultsFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = CompareResultsFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()